# This is a corrected CI workflow for a Node.js backend and React.js frontend.
# It will run on every push and pull request to the 'main' branch.

name: Node.js and React CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    # 1. Checks-out your repository.
    #    The "fetch-depth: 0" line is the fix. It tells the action to
    #    download the full repository history, which resolves the git error.
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. Sets up the specified version of Node.js
    #    Removed cache-dependency-path to resolve potential caching errors.
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # 3. Install server dependencies and run tests
    - name: Install and test server
      run: |
        cd server
        npm install
        npm test

    # 4. Install client dependencies, run tests, and build
    - name: Install, test, and build client
      run: |
        cd client
        npm install
        npm test
        npm run build

