# This workflow uses a single job to avoid path and caching issues.

name: Node.js and React CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checks out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetches all history to prevent git-related errors
          fetch-depth: 0

      # 2. Sets up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          # Caching is removed to fix the "paths not resolved" error

      # 3. Install backend dependencies and run tests
      - name: Install and test backend
        run: |
          cd server
          npm install
          npm test

      # 4. Install frontend dependencies, test, and build
      - name: Install, test, and build frontend
        run: |
          cd client
          npm install
          npm test
          npm run build

