# This workflow includes a debugging step to list all files.

name: Node.js and React CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checks out the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. DEBUGGING STEP: List all files
      # This will show the exact folder structure in the logs.
      - name: List files in the repository
        run: ls -R

      # 3. Sets up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      # 4. Install and test backend
      - name: Install and test backend
        run: |
          cd server
          npm install
          npm test

      # 5. Install, test, and build frontend
      - name: Install, test, and build frontend
        run: |
          cd client
          npm install
          npm test
          npm run build

